project_id = "ayqvnclmnepqyhvjqxjy"

[functions.send-invite-email]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = true

[functions.handle-stripe-webhook]
verify_jwt = false

[functions.validate-file-upload]
verify_jwt = true

[functions.data-retention-cleanup]
verify_jwt = false