// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ayqvnclmnepqyhvjqxjy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF5cXZuY2xtbmVwcXlodmpxeGp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxMjUzMTUsImV4cCI6MjA2OTcwMTMxNX0.8VIKJEes7MISktoJ9OW4AgFiIJdKKfOa5OfscS5CYqg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});